language: ruby
rbenv:
- 2.5.3
cache: bundler
env:
  global:
    secure: QxracpRoFXLBl0moh7Cc/r5PnGWGi+6Njhw9BM2dRfTqZq/Fssp0T9btBxc2qNsXf1ZdbWgDV7uK85k9/qoHvhIAl0wItUgq+NTg2q3ZcC25WBJrNPRcI37fNa4LsQ4ZOkeCT6pWwMZawOMEjv8tg22RxaZPGaalxE6X0APQluPzHXz9m6rFhtKRLyc2DLKwWpyYgolX4nqJvo3djMqmzHhKvYIGnTUQqbq0gKx8Caq9pUTxlnD76wYJ4aBO1s6xYOGOGP/czWPOgkPtexfEIw0YoCIkQtHjaCrHUYJVaizIbs0mQBhJoS0WVvrJWxC1ATaMtG6Ts3hSSwwLLp2MZzUFq6cv02wxQdIyNYGYzR+wm+htlixKvX1ZMpdGEDypsOit0rAQhKSahZoj5yr9fZNbQhe/5zlMDWCt5Q1B4WaSby0853xAf0hXGnWalucjREsCLhwkerfeGe70y1C8R8gAa5nK6N3T8rO1Kn6aAnJ3ja95fVMeXNPS56j+qV3Sp2ycWXxSD9fnfVsAVfCz7vErOKPLxYVaQZRtgFpOktMLK5cp6K/a7ZemYYrnjv8ePtn4JdYMl8iUxyklyU7QyadTZmb0Kr6iCNordo4fsL7ixKa0YC9BiP5NjSPj3gDtYXXsL2grnp13w1xc2RBrjSHZ0HmoPDI996N3Bu2GQj4=
deploy:
  provider: heroku
  api_key:
    secure: qSrp4gN9gqsMilGesUBtfOCpPmR3d2wZEQ+fsCZ4WpZWyFm5xHPOqbMJOQISPSRlUc0cbRTba2xT7gU/Zn/AGqWKUivBGlZaqfoBdQqzupbt0A4Bkf9j3l7jjHWMj2hK0dpj9EnJYeD2uvsVzznQTAxcit8ZHRNhn4kDR0rsJWxWTGXQGRBPoxJ/JSOeU5fVQ4VjB3RB1OfWXQdvMoOvdkM7QefTHY1/tz4tb1jHvVlsI7BWnnMrfue0hcKSUmv1HVjIGR7AIMXPvfNxejzXpCKmw8qxpHLQuEhDVUzltzklnGN966Ovb9V7Ds/0B02oIo9R8yOesoP/lK2wns/gm/kpMxhCxpd3vu+kKalREQqDNo7BivXJXAgIxs3bYsE9g299yrHfT0ptYQrW4BXqPM0Q8jdR/3gtAwi4R5RSnm6Zy02BTFmBCsxEW8Xe9yW2lDyghJoldiCmFUeimjK3UL5YrJkpLEeIPcwVJk4XRTYmUhCjoduboShz6/h94JwhlAi/h/v+ov6gpJNMYMeuyUK0xBtgqAM8ljmC+Mrc9zJUadZZrpL3dcjWd0iswF4IC5TrvbnvcUmnPeIKNvERvlYqG7SLALuZG8omUza9EBEWMkU06jTpAsLYQLpHg1FdSnpbDKvNyhCSAikUePuWN27WqCF+kHZoLYnPXt8fdnk=
  app: flight-api-service
  on:
    repo: GetThatFlightOut/Flight-API
    branch: main
  skip_cleanup: 'true'
